version: "3.9"

services:
  api:
    image: api
    ports:
      - "8050:8050"
    networks:
      - app-net

  prometheus:
    image: prometheus
    ports:
      - "9090:9090"
    networks:
      - app-net

  grafana:
    image: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat